sudo: required
services:
  - docker

before install:
  - docker build -t pchiviyski/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pchiviyski/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker2"
  env: "Docker2-env"
  bucket_name: "elasticbeanstalk-us-east-2-418371522922"
  bucket_path: "docker2"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_acces_key: "$AWS_SECRET_KEY"