sudo: required
services:
  - docker

before install:
  - docker build -t pchiviyski/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pchiviyski/docker-react npm run test -- --coverage
